/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.sitata.googleplus;

import org.appcelerator.kroll.KrollEventCallback;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="TitaniumGooglePlus", id="com.sitata.googleplus")
public class TitaniumGooglePlusModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TitaniumGooglePlusModule";
	private static final boolean DBG = TiConfig.LOGD;
	
	private String mClientId;
	private Object[] mScopes;
	private KrollEventCallback successCallback;
	private KrollEventCallback errorCallback;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TitaniumGooglePlusModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void signin(KrollDict props)
	{
		if (props.containsKey("success")) {
			successCallback = (KrollEventCallback) props.get("success");
		}
		if (props.containsKey("error")) {
			errorCallback = (KrollEventCallback) props.get("error");
		}
		
		// TODO
	}
	
	@Kroll.method
	public void signout() {
		// TODO
	}
	
	@Kroll.method
	public void disconnect() {
		// TODO
	}
	
	@Kroll.method
	public Boolean isLoggedIn() {
		return false; // TODO
	}

	// Properties
	@Kroll.getProperty @Kroll.method
	public void setClientId(String value)
	{
		mClientId = value;
	}
	
	@Kroll.getProperty @Kroll.method
	public String getClientId() {
		return mClientId;
	}

	@Kroll.getProperty @Kroll.method
	public void setScopes(Object[] value)
	{
		mScopes = value;
	}
	
	@Kroll.getProperty @Kroll.method
	public Object[] getScopes() {
		return mScopes;
	}

}

